#!/bin/bash

###############################################################################
# Pull Request Creation Handler
#
# Creates a GitHub PR using GitHub CLI (gh) for documentation updates
#
# Usage: ./create-pr.sh <project-name> <branch-name> <commit-sha> <trigger-event>
###############################################################################

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Input validation
if [ $# -lt 2 ]; then
    echo -e "${RED}Error: Insufficient arguments${NC}"
    echo "Usage: $0 <project-name> <branch-name> [commit-sha] [trigger-event]"
    exit 1
fi

PROJECT_NAME="$1"
BRANCH_NAME="$2"
COMMIT_SHA="${3:-unknown}"
TRIGGER_EVENT="${4:-manual}"
WORKSPACE_PATH="${WORKSPACE_PATH:-/home/ubuntu/workspace/$PROJECT_NAME}"

echo -e "${GREEN}=== Creating Pull Request ===${NC}"
echo "Project: $PROJECT_NAME"
echo "Branch: $BRANCH_NAME"

# Change to project workspace
cd "$WORKSPACE_PATH" || {
    echo -e "${RED}Error: Workspace path not found: $WORKSPACE_PATH${NC}"
    exit 1
}

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo -e "${RED}Error: GitHub CLI (gh) is not installed${NC}"
    echo "Install it with: sudo apt install gh"
    exit 1
fi

# Authenticate with GitHub CLI using token
if [ -n "${GITHUB_TOKEN:-}" ]; then
    echo "$GITHUB_TOKEN" | gh auth login --with-token
fi

# Prepare PR title and body
PR_TITLE="${PR_TITLE:-📚 Auto-update documentation}"
PR_BODY="This PR was automatically generated by the Documentation Automation Hub.

**Changes:**
- Updated codebase documentation using Cartographer
- Regenerated CODEBASE_MAP.md with latest code analysis

**Details:**
- **Triggered by:** \`${TRIGGER_EVENT}\`
- **Source commit:** \`${COMMIT_SHA}\`
- **Generated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")

**Review Checklist:**
- [ ] Documentation accurately reflects current codebase
- [ ] No sensitive information exposed
- [ ] File paths and structure are correct
- [ ] Links and references are valid

---

*This is an automated PR. Please review the changes before merging.*
*After merge, the service will be automatically restarted.*"

# Create PR
echo -e "${YELLOW}Creating pull request...${NC}"

# Run gh pr create and capture exit code properly
set +e  # Temporarily disable exit on error
PR_OUTPUT=$(gh pr create \
    --title "$PR_TITLE" \
    --body "$PR_BODY" \
    --base main \
    --head "$BRANCH_NAME" \
    --label "documentation,automated" \
    --assignee "@me" 2>&1)
PR_EXIT_CODE=$?
set -e  # Re-enable exit on error

if [ $PR_EXIT_CODE -eq 0 ]; then
    echo -e "${GREEN}Pull request created successfully!${NC}"
    echo "URL: $PR_OUTPUT"

    # Extract PR number from URL
    PR_NUMBER=$(echo "$PR_OUTPUT" | grep -oP '/pull/\K\d+' || echo "unknown")

    # Optionally: Enable auto-merge if branch is up-to-date and checks pass
    # gh pr merge "$PR_NUMBER" --auto --squash

    echo "PR Number: #$PR_NUMBER"
else
    echo -e "${RED}Failed to create pull request${NC}"
    echo "Output: $PR_OUTPUT"
    echo "Exit code: $PR_EXIT_CODE"
    exit 1
fi

exit 0
