#!/bin/bash

###############################################################################
# Documentation Generation Handler
#
# Generates documentation using Claude Code CLI and Cartographer skill,
# then creates a PR with the changes.
#
# Usage: ./generate-docs.sh <project-name>
###############################################################################

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Input validation
if [ -z "${1:-}" ]; then
    echo -e "${RED}Error: Project name required${NC}"
    echo "Usage: $0 <project-name>"
    exit 1
fi

PROJECT_NAME="$1"
WORKSPACE_PATH="${WORKSPACE_PATH:-/home/ubuntu/workspace/$PROJECT_NAME}"
COMMIT_SHA="${COMMIT_SHA:-unknown}"
TRIGGER_EVENT="${TRIGGER_EVENT:-manual}"
PR_BRANCH_PREFIX="${PR_BRANCH_PREFIX:-docs/auto-update-}"
TIMESTAMP=$(date +%Y%m%d-%H%M%S)
BRANCH_NAME="${PR_BRANCH_PREFIX}${TIMESTAMP}"

echo -e "${GREEN}=== Starting Documentation Generation ===${NC}"
echo "Project: $PROJECT_NAME"
echo "Workspace: $WORKSPACE_PATH"
echo "Branch: $BRANCH_NAME"
echo "Commit: $COMMIT_SHA"

# Change to project workspace
cd "$WORKSPACE_PATH" || {
    echo -e "${RED}Error: Workspace path not found: $WORKSPACE_PATH${NC}"
    exit 1
}

# Ensure we're on the default branch and up-to-date
echo -e "${YELLOW}Fetching latest changes...${NC}"
git fetch origin 2>&1
git checkout main 2>&1
git pull origin main 2>&1

# Create feature branch for documentation updates
echo -e "${YELLOW}Creating feature branch: $BRANCH_NAME${NC}"
git checkout -b "$BRANCH_NAME" 2>&1

# Run Cartographer using Claude Code CLI
echo -e "${YELLOW}Running Cartographer to generate documentation...${NC}"
CLAUDE_CODE_PATH="${CLAUDE_CODE_PATH:-/usr/local/bin/claude}"

if [ ! -x "$CLAUDE_CODE_PATH" ]; then
    echo -e "${RED}Error: Claude Code CLI not found or not executable: $CLAUDE_CODE_PATH${NC}"
    exit 1
fi

# Execute Cartographer skill programmatically using Claude API
# This approach mimics Cartographer's workflow but runs non-interactively
echo -e "${YELLOW}Invoking Cartographer via programmatic Claude API workflow...${NC}"

# Get the handler directory (where this script is located)
HANDLER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HUB_ROOT="$(dirname "$HANDLER_DIR")"
CARTOGRAPHER_SCRIPT="$HUB_ROOT/utils/invoke-cartographer-programmatic.mjs"
LOG_FILE="/tmp/cartographer-${PROJECT_NAME}-${TIMESTAMP}.log"

# Check if the invocation script exists
if [ ! -f "$CARTOGRAPHER_SCRIPT" ]; then
    echo -e "${RED}Error: Cartographer invocation script not found: $CARTOGRAPHER_SCRIPT${NC}"
    exit 1
fi

# Run Cartographer programmatically using Claude API
node "$CARTOGRAPHER_SCRIPT" "$WORKSPACE_PATH" "$LOG_FILE"
CARTOGRAPHER_EXIT_CODE=$?

if [ $CARTOGRAPHER_EXIT_CODE -ne 0 ]; then
    echo -e "${RED}Error: Cartographer execution failed (exit code: $CARTOGRAPHER_EXIT_CODE)${NC}"
    echo -e "${YELLOW}Check log file for details: $LOG_FILE${NC}"
    # Don't exit yet - let the documentation check below handle it
fi

echo -e "${GREEN}Cartographer execution completed${NC}"

# Check if documentation was generated
if [ ! -f "docs/CODEBASE_MAP.md" ]; then
    echo -e "${RED}Error: Documentation generation failed - CODEBASE_MAP.md not found${NC}"
    # Clean up branch
    git checkout main
    git branch -D "$BRANCH_NAME" 2>/dev/null || true
    exit 1
fi

# Check if there are actual changes (including untracked files)
if ! git status --porcelain docs/ | grep -q .; then
    echo -e "${YELLOW}No changes detected in documentation${NC}"
    # Clean up branch
    git checkout main
    git branch -D "$BRANCH_NAME" 2>/dev/null || true
    exit 0
fi

# Stage and commit changes
echo -e "${YELLOW}Committing documentation changes...${NC}"
git add docs/
COMMIT_MESSAGE="${COMMIT_MESSAGE:-docs: auto-update documentation [skip ci]

Generated by Documentation Automation Hub
Triggered by: ${TRIGGER_EVENT}
Source commit: ${COMMIT_SHA}
}"

git commit -m "$COMMIT_MESSAGE"

# Push branch to remote
echo -e "${YELLOW}Pushing branch to remote...${NC}"
git push -u origin "$BRANCH_NAME" 2>&1

# Create PR using create-pr.sh handler
echo -e "${YELLOW}Creating pull request...${NC}"
HANDLER_DIR="$(dirname "$0")"
bash "$HANDLER_DIR/create-pr.sh" "$PROJECT_NAME" "$BRANCH_NAME" "$COMMIT_SHA" "$TRIGGER_EVENT"

echo -e "${GREEN}=== Documentation Generation Complete ===${NC}"
echo "Branch: $BRANCH_NAME"
echo "Check GitHub for the pull request"

# Return to main branch
git checkout main 2>&1

exit 0
